/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.unotext.unoText.CumulAjout;
import org.xtext.example.unotext.unoText.UnoTextPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cumul Ajout</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.CumulAjoutImpl#isPlus2 <em>Plus2</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.CumulAjoutImpl#isPlus4 <em>Plus4</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CumulAjoutImpl extends MinimalEObjectImpl.Container implements CumulAjout
{
  /**
   * The default value of the '{@link #isPlus2() <em>Plus2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPlus2()
   * @generated
   * @ordered
   */
  protected static final boolean PLUS2_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isPlus2() <em>Plus2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPlus2()
   * @generated
   * @ordered
   */
  protected boolean plus2 = PLUS2_EDEFAULT;

  /**
   * The default value of the '{@link #isPlus4() <em>Plus4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPlus4()
   * @generated
   * @ordered
   */
  protected static final boolean PLUS4_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isPlus4() <em>Plus4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPlus4()
   * @generated
   * @ordered
   */
  protected boolean plus4 = PLUS4_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CumulAjoutImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoTextPackage.Literals.CUMUL_AJOUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isPlus2()
  {
    return plus2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlus2(boolean newPlus2)
  {
    boolean oldPlus2 = plus2;
    plus2 = newPlus2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.CUMUL_AJOUT__PLUS2, oldPlus2, plus2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isPlus4()
  {
    return plus4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlus4(boolean newPlus4)
  {
    boolean oldPlus4 = plus4;
    plus4 = newPlus4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.CUMUL_AJOUT__PLUS4, oldPlus4, plus4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoTextPackage.CUMUL_AJOUT__PLUS2:
        return isPlus2();
      case UnoTextPackage.CUMUL_AJOUT__PLUS4:
        return isPlus4();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoTextPackage.CUMUL_AJOUT__PLUS2:
        setPlus2((Boolean)newValue);
        return;
      case UnoTextPackage.CUMUL_AJOUT__PLUS4:
        setPlus4((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.CUMUL_AJOUT__PLUS2:
        setPlus2(PLUS2_EDEFAULT);
        return;
      case UnoTextPackage.CUMUL_AJOUT__PLUS4:
        setPlus4(PLUS4_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.CUMUL_AJOUT__PLUS2:
        return plus2 != PLUS2_EDEFAULT;
      case UnoTextPackage.CUMUL_AJOUT__PLUS4:
        return plus4 != PLUS4_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (plus2: ");
    result.append(plus2);
    result.append(", plus4: ");
    result.append(plus4);
    result.append(')');
    return result.toString();
  }

} //CumulAjoutImpl
