/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.unotext.unoText.UnoTextPackage;
import org.xtext.example.unotext.unoText.Uno_Rule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uno Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Uno_RuleImpl extends MinimalEObjectImpl.Container implements Uno_Rule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Uno_RuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoTextPackage.Literals.UNO_RULE;
  }

} //Uno_RuleImpl
