/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.unotext.unoText.UnoTextPackage;
import org.xtext.example.unotext.unoText.Uno_Classic;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uno Classic</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isUnoChallenge <em>Uno Challenge</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isCarte0_7 <em>Carte0 7</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isCarteIdentique <em>Carte Identique</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isCumulAjout <em>Cumul Ajout</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isSuite <em>Suite</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isPioche <em>Pioche</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isMore4 <em>More4</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isTempsLimite <em>Temps Limite</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isMauvaiseCarte <em>Mauvaise Carte</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isEquipe <em>Equipe</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isCarteVisibles <em>Carte Visibles</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isFinManche <em>Fin Manche</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isThreeHands <em>Three Hands</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isThreePiles <em>Three Piles</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#isSpecialCard <em>Special Card</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl#getGameOver <em>Game Over</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Uno_ClassicImpl extends Uno_RuleImpl implements Uno_Classic
{
  /**
   * The default value of the '{@link #isUnoChallenge() <em>Uno Challenge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnoChallenge()
   * @generated
   * @ordered
   */
  protected static final boolean UNO_CHALLENGE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnoChallenge() <em>Uno Challenge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnoChallenge()
   * @generated
   * @ordered
   */
  protected boolean unoChallenge = UNO_CHALLENGE_EDEFAULT;

  /**
   * The default value of the '{@link #isCarte0_7() <em>Carte0 7</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarte0_7()
   * @generated
   * @ordered
   */
  protected static final boolean CARTE0_7_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCarte0_7() <em>Carte0 7</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarte0_7()
   * @generated
   * @ordered
   */
  protected boolean carte0_7 = CARTE0_7_EDEFAULT;

  /**
   * The default value of the '{@link #isCarteIdentique() <em>Carte Identique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteIdentique()
   * @generated
   * @ordered
   */
  protected static final boolean CARTE_IDENTIQUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCarteIdentique() <em>Carte Identique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteIdentique()
   * @generated
   * @ordered
   */
  protected boolean carteIdentique = CARTE_IDENTIQUE_EDEFAULT;

  /**
   * The default value of the '{@link #isCumulAjout() <em>Cumul Ajout</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCumulAjout()
   * @generated
   * @ordered
   */
  protected static final boolean CUMUL_AJOUT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCumulAjout() <em>Cumul Ajout</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCumulAjout()
   * @generated
   * @ordered
   */
  protected boolean cumulAjout = CUMUL_AJOUT_EDEFAULT;

  /**
   * The default value of the '{@link #isSuite() <em>Suite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSuite()
   * @generated
   * @ordered
   */
  protected static final boolean SUITE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSuite() <em>Suite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSuite()
   * @generated
   * @ordered
   */
  protected boolean suite = SUITE_EDEFAULT;

  /**
   * The default value of the '{@link #isPioche() <em>Pioche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPioche()
   * @generated
   * @ordered
   */
  protected static final boolean PIOCHE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isPioche() <em>Pioche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPioche()
   * @generated
   * @ordered
   */
  protected boolean pioche = PIOCHE_EDEFAULT;

  /**
   * The default value of the '{@link #isMore4() <em>More4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMore4()
   * @generated
   * @ordered
   */
  protected static final boolean MORE4_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMore4() <em>More4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMore4()
   * @generated
   * @ordered
   */
  protected boolean more4 = MORE4_EDEFAULT;

  /**
   * The default value of the '{@link #isTempsLimite() <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTempsLimite()
   * @generated
   * @ordered
   */
  protected static final boolean TEMPS_LIMITE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isTempsLimite() <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isTempsLimite()
   * @generated
   * @ordered
   */
  protected boolean tempsLimite = TEMPS_LIMITE_EDEFAULT;

  /**
   * The default value of the '{@link #isMauvaiseCarte() <em>Mauvaise Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMauvaiseCarte()
   * @generated
   * @ordered
   */
  protected static final boolean MAUVAISE_CARTE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMauvaiseCarte() <em>Mauvaise Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMauvaiseCarte()
   * @generated
   * @ordered
   */
  protected boolean mauvaiseCarte = MAUVAISE_CARTE_EDEFAULT;

  /**
   * The default value of the '{@link #isEquipe() <em>Equipe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEquipe()
   * @generated
   * @ordered
   */
  protected static final boolean EQUIPE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEquipe() <em>Equipe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEquipe()
   * @generated
   * @ordered
   */
  protected boolean equipe = EQUIPE_EDEFAULT;

  /**
   * The default value of the '{@link #isCarteVisibles() <em>Carte Visibles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteVisibles()
   * @generated
   * @ordered
   */
  protected static final boolean CARTE_VISIBLES_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCarteVisibles() <em>Carte Visibles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteVisibles()
   * @generated
   * @ordered
   */
  protected boolean carteVisibles = CARTE_VISIBLES_EDEFAULT;

  /**
   * The default value of the '{@link #isFinManche() <em>Fin Manche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinManche()
   * @generated
   * @ordered
   */
  protected static final boolean FIN_MANCHE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFinManche() <em>Fin Manche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFinManche()
   * @generated
   * @ordered
   */
  protected boolean finManche = FIN_MANCHE_EDEFAULT;

  /**
   * The default value of the '{@link #isThreeHands() <em>Three Hands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isThreeHands()
   * @generated
   * @ordered
   */
  protected static final boolean THREE_HANDS_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isThreeHands() <em>Three Hands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isThreeHands()
   * @generated
   * @ordered
   */
  protected boolean threeHands = THREE_HANDS_EDEFAULT;

  /**
   * The default value of the '{@link #isThreePiles() <em>Three Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isThreePiles()
   * @generated
   * @ordered
   */
  protected static final boolean THREE_PILES_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isThreePiles() <em>Three Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isThreePiles()
   * @generated
   * @ordered
   */
  protected boolean threePiles = THREE_PILES_EDEFAULT;

  /**
   * The default value of the '{@link #isSpecialCard() <em>Special Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpecialCard()
   * @generated
   * @ordered
   */
  protected static final boolean SPECIAL_CARD_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSpecialCard() <em>Special Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSpecialCard()
   * @generated
   * @ordered
   */
  protected boolean specialCard = SPECIAL_CARD_EDEFAULT;

  /**
   * The default value of the '{@link #getGameOver() <em>Game Over</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGameOver()
   * @generated
   * @ordered
   */
  protected static final String GAME_OVER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGameOver() <em>Game Over</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGameOver()
   * @generated
   * @ordered
   */
  protected String gameOver = GAME_OVER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Uno_ClassicImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoTextPackage.Literals.UNO_CLASSIC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isUnoChallenge()
  {
    return unoChallenge;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUnoChallenge(boolean newUnoChallenge)
  {
    boolean oldUnoChallenge = unoChallenge;
    unoChallenge = newUnoChallenge;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__UNO_CHALLENGE, oldUnoChallenge, unoChallenge));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCarte0_7()
  {
    return carte0_7;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCarte0_7(boolean newCarte0_7)
  {
    boolean oldCarte0_7 = carte0_7;
    carte0_7 = newCarte0_7;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__CARTE0_7, oldCarte0_7, carte0_7));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCarteIdentique()
  {
    return carteIdentique;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCarteIdentique(boolean newCarteIdentique)
  {
    boolean oldCarteIdentique = carteIdentique;
    carteIdentique = newCarteIdentique;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__CARTE_IDENTIQUE, oldCarteIdentique, carteIdentique));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCumulAjout()
  {
    return cumulAjout;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumulAjout(boolean newCumulAjout)
  {
    boolean oldCumulAjout = cumulAjout;
    cumulAjout = newCumulAjout;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__CUMUL_AJOUT, oldCumulAjout, cumulAjout));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isSuite()
  {
    return suite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuite(boolean newSuite)
  {
    boolean oldSuite = suite;
    suite = newSuite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__SUITE, oldSuite, suite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isPioche()
  {
    return pioche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPioche(boolean newPioche)
  {
    boolean oldPioche = pioche;
    pioche = newPioche;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__PIOCHE, oldPioche, pioche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isMore4()
  {
    return more4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMore4(boolean newMore4)
  {
    boolean oldMore4 = more4;
    more4 = newMore4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__MORE4, oldMore4, more4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isTempsLimite()
  {
    return tempsLimite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTempsLimite(boolean newTempsLimite)
  {
    boolean oldTempsLimite = tempsLimite;
    tempsLimite = newTempsLimite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__TEMPS_LIMITE, oldTempsLimite, tempsLimite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isMauvaiseCarte()
  {
    return mauvaiseCarte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMauvaiseCarte(boolean newMauvaiseCarte)
  {
    boolean oldMauvaiseCarte = mauvaiseCarte;
    mauvaiseCarte = newMauvaiseCarte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__MAUVAISE_CARTE, oldMauvaiseCarte, mauvaiseCarte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEquipe()
  {
    return equipe;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEquipe(boolean newEquipe)
  {
    boolean oldEquipe = equipe;
    equipe = newEquipe;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__EQUIPE, oldEquipe, equipe));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCarteVisibles()
  {
    return carteVisibles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCarteVisibles(boolean newCarteVisibles)
  {
    boolean oldCarteVisibles = carteVisibles;
    carteVisibles = newCarteVisibles;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__CARTE_VISIBLES, oldCarteVisibles, carteVisibles));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFinManche()
  {
    return finManche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinManche(boolean newFinManche)
  {
    boolean oldFinManche = finManche;
    finManche = newFinManche;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__FIN_MANCHE, oldFinManche, finManche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isThreeHands()
  {
    return threeHands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThreeHands(boolean newThreeHands)
  {
    boolean oldThreeHands = threeHands;
    threeHands = newThreeHands;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__THREE_HANDS, oldThreeHands, threeHands));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isThreePiles()
  {
    return threePiles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThreePiles(boolean newThreePiles)
  {
    boolean oldThreePiles = threePiles;
    threePiles = newThreePiles;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__THREE_PILES, oldThreePiles, threePiles));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isSpecialCard()
  {
    return specialCard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpecialCard(boolean newSpecialCard)
  {
    boolean oldSpecialCard = specialCard;
    specialCard = newSpecialCard;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__SPECIAL_CARD, oldSpecialCard, specialCard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGameOver()
  {
    return gameOver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGameOver(String newGameOver)
  {
    String oldGameOver = gameOver;
    gameOver = newGameOver;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_CLASSIC__GAME_OVER, oldGameOver, gameOver));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_CLASSIC__UNO_CHALLENGE:
        return isUnoChallenge();
      case UnoTextPackage.UNO_CLASSIC__CARTE0_7:
        return isCarte0_7();
      case UnoTextPackage.UNO_CLASSIC__CARTE_IDENTIQUE:
        return isCarteIdentique();
      case UnoTextPackage.UNO_CLASSIC__CUMUL_AJOUT:
        return isCumulAjout();
      case UnoTextPackage.UNO_CLASSIC__SUITE:
        return isSuite();
      case UnoTextPackage.UNO_CLASSIC__PIOCHE:
        return isPioche();
      case UnoTextPackage.UNO_CLASSIC__MORE4:
        return isMore4();
      case UnoTextPackage.UNO_CLASSIC__TEMPS_LIMITE:
        return isTempsLimite();
      case UnoTextPackage.UNO_CLASSIC__MAUVAISE_CARTE:
        return isMauvaiseCarte();
      case UnoTextPackage.UNO_CLASSIC__EQUIPE:
        return isEquipe();
      case UnoTextPackage.UNO_CLASSIC__CARTE_VISIBLES:
        return isCarteVisibles();
      case UnoTextPackage.UNO_CLASSIC__FIN_MANCHE:
        return isFinManche();
      case UnoTextPackage.UNO_CLASSIC__THREE_HANDS:
        return isThreeHands();
      case UnoTextPackage.UNO_CLASSIC__THREE_PILES:
        return isThreePiles();
      case UnoTextPackage.UNO_CLASSIC__SPECIAL_CARD:
        return isSpecialCard();
      case UnoTextPackage.UNO_CLASSIC__GAME_OVER:
        return getGameOver();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_CLASSIC__UNO_CHALLENGE:
        setUnoChallenge((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE0_7:
        setCarte0_7((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE_IDENTIQUE:
        setCarteIdentique((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__CUMUL_AJOUT:
        setCumulAjout((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__SUITE:
        setSuite((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__PIOCHE:
        setPioche((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__MORE4:
        setMore4((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__TEMPS_LIMITE:
        setTempsLimite((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__MAUVAISE_CARTE:
        setMauvaiseCarte((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__EQUIPE:
        setEquipe((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE_VISIBLES:
        setCarteVisibles((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__FIN_MANCHE:
        setFinManche((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__THREE_HANDS:
        setThreeHands((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__THREE_PILES:
        setThreePiles((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__SPECIAL_CARD:
        setSpecialCard((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_CLASSIC__GAME_OVER:
        setGameOver((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_CLASSIC__UNO_CHALLENGE:
        setUnoChallenge(UNO_CHALLENGE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE0_7:
        setCarte0_7(CARTE0_7_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE_IDENTIQUE:
        setCarteIdentique(CARTE_IDENTIQUE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__CUMUL_AJOUT:
        setCumulAjout(CUMUL_AJOUT_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__SUITE:
        setSuite(SUITE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__PIOCHE:
        setPioche(PIOCHE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__MORE4:
        setMore4(MORE4_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__TEMPS_LIMITE:
        setTempsLimite(TEMPS_LIMITE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__MAUVAISE_CARTE:
        setMauvaiseCarte(MAUVAISE_CARTE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__EQUIPE:
        setEquipe(EQUIPE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__CARTE_VISIBLES:
        setCarteVisibles(CARTE_VISIBLES_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__FIN_MANCHE:
        setFinManche(FIN_MANCHE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__THREE_HANDS:
        setThreeHands(THREE_HANDS_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__THREE_PILES:
        setThreePiles(THREE_PILES_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__SPECIAL_CARD:
        setSpecialCard(SPECIAL_CARD_EDEFAULT);
        return;
      case UnoTextPackage.UNO_CLASSIC__GAME_OVER:
        setGameOver(GAME_OVER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_CLASSIC__UNO_CHALLENGE:
        return unoChallenge != UNO_CHALLENGE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__CARTE0_7:
        return carte0_7 != CARTE0_7_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__CARTE_IDENTIQUE:
        return carteIdentique != CARTE_IDENTIQUE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__CUMUL_AJOUT:
        return cumulAjout != CUMUL_AJOUT_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__SUITE:
        return suite != SUITE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__PIOCHE:
        return pioche != PIOCHE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__MORE4:
        return more4 != MORE4_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__TEMPS_LIMITE:
        return tempsLimite != TEMPS_LIMITE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__MAUVAISE_CARTE:
        return mauvaiseCarte != MAUVAISE_CARTE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__EQUIPE:
        return equipe != EQUIPE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__CARTE_VISIBLES:
        return carteVisibles != CARTE_VISIBLES_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__FIN_MANCHE:
        return finManche != FIN_MANCHE_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__THREE_HANDS:
        return threeHands != THREE_HANDS_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__THREE_PILES:
        return threePiles != THREE_PILES_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__SPECIAL_CARD:
        return specialCard != SPECIAL_CARD_EDEFAULT;
      case UnoTextPackage.UNO_CLASSIC__GAME_OVER:
        return GAME_OVER_EDEFAULT == null ? gameOver != null : !GAME_OVER_EDEFAULT.equals(gameOver);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (unoChallenge: ");
    result.append(unoChallenge);
    result.append(", carte0_7: ");
    result.append(carte0_7);
    result.append(", carteIdentique: ");
    result.append(carteIdentique);
    result.append(", cumulAjout: ");
    result.append(cumulAjout);
    result.append(", suite: ");
    result.append(suite);
    result.append(", pioche: ");
    result.append(pioche);
    result.append(", more4: ");
    result.append(more4);
    result.append(", tempsLimite: ");
    result.append(tempsLimite);
    result.append(", mauvaiseCarte: ");
    result.append(mauvaiseCarte);
    result.append(", equipe: ");
    result.append(equipe);
    result.append(", carteVisibles: ");
    result.append(carteVisibles);
    result.append(", finManche: ");
    result.append(finManche);
    result.append(", threeHands: ");
    result.append(threeHands);
    result.append(", threePiles: ");
    result.append(threePiles);
    result.append(", specialCard: ");
    result.append(specialCard);
    result.append(", gameOver: ");
    result.append(gameOver);
    result.append(')');
    return result.toString();
  }

} //Uno_ClassicImpl
