/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.unotext.unoText.UnoOlypique;
import org.xtext.example.unotext.unoText.UnoTextPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uno Olypique</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getTribunalPopulaire <em>Tribunal Populaire</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getDistributionAleatoire <em>Distribution Aleatoire</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getSensDefini <em>Sens Defini</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getChangementDonneur <em>Changement Donneur</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getVueDesCartesApres1erPose <em>Vue Des Cartes Apres1er Pose</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getDonneurPremierose <em>Donneur Premierose</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getJeuRapide <em>Jeu Rapide</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getInterception <em>Interception</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getDeuxCartesIdentiques <em>Deux Cartes Identiques</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getDecisionCarte <em>Decision Carte</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getSurenchere <em>Surenchere</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#isCartezero <em>Cartezero</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#isCarteSept <em>Carte Sept</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getCarte2 <em>Carte2</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl#getValeurCarte <em>Valeur Carte</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UnoOlypiqueImpl extends Uno_RuleImpl implements UnoOlypique
{
  /**
   * The default value of the '{@link #getTribunalPopulaire() <em>Tribunal Populaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTribunalPopulaire()
   * @generated
   * @ordered
   */
  protected static final String TRIBUNAL_POPULAIRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTribunalPopulaire() <em>Tribunal Populaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTribunalPopulaire()
   * @generated
   * @ordered
   */
  protected String tribunalPopulaire = TRIBUNAL_POPULAIRE_EDEFAULT;

  /**
   * The default value of the '{@link #getDistributionAleatoire() <em>Distribution Aleatoire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistributionAleatoire()
   * @generated
   * @ordered
   */
  protected static final String DISTRIBUTION_ALEATOIRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDistributionAleatoire() <em>Distribution Aleatoire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDistributionAleatoire()
   * @generated
   * @ordered
   */
  protected String distributionAleatoire = DISTRIBUTION_ALEATOIRE_EDEFAULT;

  /**
   * The default value of the '{@link #getSensDefini() <em>Sens Defini</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSensDefini()
   * @generated
   * @ordered
   */
  protected static final String SENS_DEFINI_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSensDefini() <em>Sens Defini</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSensDefini()
   * @generated
   * @ordered
   */
  protected String sensDefini = SENS_DEFINI_EDEFAULT;

  /**
   * The default value of the '{@link #getChangementDonneur() <em>Changement Donneur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChangementDonneur()
   * @generated
   * @ordered
   */
  protected static final String CHANGEMENT_DONNEUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getChangementDonneur() <em>Changement Donneur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChangementDonneur()
   * @generated
   * @ordered
   */
  protected String changementDonneur = CHANGEMENT_DONNEUR_EDEFAULT;

  /**
   * The default value of the '{@link #getVueDesCartesApres1erPose() <em>Vue Des Cartes Apres1er Pose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVueDesCartesApres1erPose()
   * @generated
   * @ordered
   */
  protected static final String VUE_DES_CARTES_APRES1ER_POSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVueDesCartesApres1erPose() <em>Vue Des Cartes Apres1er Pose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVueDesCartesApres1erPose()
   * @generated
   * @ordered
   */
  protected String vueDesCartesApres1erPose = VUE_DES_CARTES_APRES1ER_POSE_EDEFAULT;

  /**
   * The default value of the '{@link #getDonneurPremierose() <em>Donneur Premierose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDonneurPremierose()
   * @generated
   * @ordered
   */
  protected static final String DONNEUR_PREMIEROSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDonneurPremierose() <em>Donneur Premierose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDonneurPremierose()
   * @generated
   * @ordered
   */
  protected String donneurPremierose = DONNEUR_PREMIEROSE_EDEFAULT;

  /**
   * The default value of the '{@link #getJeuRapide() <em>Jeu Rapide</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJeuRapide()
   * @generated
   * @ordered
   */
  protected static final String JEU_RAPIDE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJeuRapide() <em>Jeu Rapide</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJeuRapide()
   * @generated
   * @ordered
   */
  protected String jeuRapide = JEU_RAPIDE_EDEFAULT;

  /**
   * The default value of the '{@link #getInterception() <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterception()
   * @generated
   * @ordered
   */
  protected static final String INTERCEPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInterception() <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInterception()
   * @generated
   * @ordered
   */
  protected String interception = INTERCEPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getDeuxCartesIdentiques() <em>Deux Cartes Identiques</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeuxCartesIdentiques()
   * @generated
   * @ordered
   */
  protected static final String DEUX_CARTES_IDENTIQUES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeuxCartesIdentiques() <em>Deux Cartes Identiques</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeuxCartesIdentiques()
   * @generated
   * @ordered
   */
  protected String deuxCartesIdentiques = DEUX_CARTES_IDENTIQUES_EDEFAULT;

  /**
   * The default value of the '{@link #getDecisionCarte() <em>Decision Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionCarte()
   * @generated
   * @ordered
   */
  protected static final String DECISION_CARTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDecisionCarte() <em>Decision Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDecisionCarte()
   * @generated
   * @ordered
   */
  protected String decisionCarte = DECISION_CARTE_EDEFAULT;

  /**
   * The default value of the '{@link #getSurenchere() <em>Surenchere</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurenchere()
   * @generated
   * @ordered
   */
  protected static final String SURENCHERE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSurenchere() <em>Surenchere</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurenchere()
   * @generated
   * @ordered
   */
  protected String surenchere = SURENCHERE_EDEFAULT;

  /**
   * The default value of the '{@link #isCartezero() <em>Cartezero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCartezero()
   * @generated
   * @ordered
   */
  protected static final boolean CARTEZERO_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCartezero() <em>Cartezero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCartezero()
   * @generated
   * @ordered
   */
  protected boolean cartezero = CARTEZERO_EDEFAULT;

  /**
   * The default value of the '{@link #isCarteSept() <em>Carte Sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteSept()
   * @generated
   * @ordered
   */
  protected static final boolean CARTE_SEPT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCarteSept() <em>Carte Sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCarteSept()
   * @generated
   * @ordered
   */
  protected boolean carteSept = CARTE_SEPT_EDEFAULT;

  /**
   * The default value of the '{@link #getCarte2() <em>Carte2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCarte2()
   * @generated
   * @ordered
   */
  protected static final String CARTE2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCarte2() <em>Carte2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCarte2()
   * @generated
   * @ordered
   */
  protected String carte2 = CARTE2_EDEFAULT;

  /**
   * The default value of the '{@link #getValeurCarte() <em>Valeur Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValeurCarte()
   * @generated
   * @ordered
   */
  protected static final String VALEUR_CARTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValeurCarte() <em>Valeur Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValeurCarte()
   * @generated
   * @ordered
   */
  protected String valeurCarte = VALEUR_CARTE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UnoOlypiqueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UnoTextPackage.Literals.UNO_OLYPIQUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTribunalPopulaire()
  {
    return tribunalPopulaire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTribunalPopulaire(String newTribunalPopulaire)
  {
    String oldTribunalPopulaire = tribunalPopulaire;
    tribunalPopulaire = newTribunalPopulaire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__TRIBUNAL_POPULAIRE, oldTribunalPopulaire, tribunalPopulaire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDistributionAleatoire()
  {
    return distributionAleatoire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDistributionAleatoire(String newDistributionAleatoire)
  {
    String oldDistributionAleatoire = distributionAleatoire;
    distributionAleatoire = newDistributionAleatoire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE, oldDistributionAleatoire, distributionAleatoire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSensDefini()
  {
    return sensDefini;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSensDefini(String newSensDefini)
  {
    String oldSensDefini = sensDefini;
    sensDefini = newSensDefini;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__SENS_DEFINI, oldSensDefini, sensDefini));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getChangementDonneur()
  {
    return changementDonneur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChangementDonneur(String newChangementDonneur)
  {
    String oldChangementDonneur = changementDonneur;
    changementDonneur = newChangementDonneur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__CHANGEMENT_DONNEUR, oldChangementDonneur, changementDonneur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVueDesCartesApres1erPose()
  {
    return vueDesCartesApres1erPose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVueDesCartesApres1erPose(String newVueDesCartesApres1erPose)
  {
    String oldVueDesCartesApres1erPose = vueDesCartesApres1erPose;
    vueDesCartesApres1erPose = newVueDesCartesApres1erPose;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE, oldVueDesCartesApres1erPose, vueDesCartesApres1erPose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDonneurPremierose()
  {
    return donneurPremierose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDonneurPremierose(String newDonneurPremierose)
  {
    String oldDonneurPremierose = donneurPremierose;
    donneurPremierose = newDonneurPremierose;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__DONNEUR_PREMIEROSE, oldDonneurPremierose, donneurPremierose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJeuRapide()
  {
    return jeuRapide;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJeuRapide(String newJeuRapide)
  {
    String oldJeuRapide = jeuRapide;
    jeuRapide = newJeuRapide;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__JEU_RAPIDE, oldJeuRapide, jeuRapide));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInterception()
  {
    return interception;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInterception(String newInterception)
  {
    String oldInterception = interception;
    interception = newInterception;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__INTERCEPTION, oldInterception, interception));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDeuxCartesIdentiques()
  {
    return deuxCartesIdentiques;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeuxCartesIdentiques(String newDeuxCartesIdentiques)
  {
    String oldDeuxCartesIdentiques = deuxCartesIdentiques;
    deuxCartesIdentiques = newDeuxCartesIdentiques;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES, oldDeuxCartesIdentiques, deuxCartesIdentiques));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDecisionCarte()
  {
    return decisionCarte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDecisionCarte(String newDecisionCarte)
  {
    String oldDecisionCarte = decisionCarte;
    decisionCarte = newDecisionCarte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__DECISION_CARTE, oldDecisionCarte, decisionCarte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSurenchere()
  {
    return surenchere;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSurenchere(String newSurenchere)
  {
    String oldSurenchere = surenchere;
    surenchere = newSurenchere;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__SURENCHERE, oldSurenchere, surenchere));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCartezero()
  {
    return cartezero;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCartezero(boolean newCartezero)
  {
    boolean oldCartezero = cartezero;
    cartezero = newCartezero;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__CARTEZERO, oldCartezero, cartezero));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCarteSept()
  {
    return carteSept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCarteSept(boolean newCarteSept)
  {
    boolean oldCarteSept = carteSept;
    carteSept = newCarteSept;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__CARTE_SEPT, oldCarteSept, carteSept));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCarte2()
  {
    return carte2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCarte2(String newCarte2)
  {
    String oldCarte2 = carte2;
    carte2 = newCarte2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__CARTE2, oldCarte2, carte2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getValeurCarte()
  {
    return valeurCarte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValeurCarte(String newValeurCarte)
  {
    String oldValeurCarte = valeurCarte;
    valeurCarte = newValeurCarte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UnoTextPackage.UNO_OLYPIQUE__VALEUR_CARTE, oldValeurCarte, valeurCarte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_OLYPIQUE__TRIBUNAL_POPULAIRE:
        return getTribunalPopulaire();
      case UnoTextPackage.UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE:
        return getDistributionAleatoire();
      case UnoTextPackage.UNO_OLYPIQUE__SENS_DEFINI:
        return getSensDefini();
      case UnoTextPackage.UNO_OLYPIQUE__CHANGEMENT_DONNEUR:
        return getChangementDonneur();
      case UnoTextPackage.UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE:
        return getVueDesCartesApres1erPose();
      case UnoTextPackage.UNO_OLYPIQUE__DONNEUR_PREMIEROSE:
        return getDonneurPremierose();
      case UnoTextPackage.UNO_OLYPIQUE__JEU_RAPIDE:
        return getJeuRapide();
      case UnoTextPackage.UNO_OLYPIQUE__INTERCEPTION:
        return getInterception();
      case UnoTextPackage.UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES:
        return getDeuxCartesIdentiques();
      case UnoTextPackage.UNO_OLYPIQUE__DECISION_CARTE:
        return getDecisionCarte();
      case UnoTextPackage.UNO_OLYPIQUE__SURENCHERE:
        return getSurenchere();
      case UnoTextPackage.UNO_OLYPIQUE__CARTEZERO:
        return isCartezero();
      case UnoTextPackage.UNO_OLYPIQUE__CARTE_SEPT:
        return isCarteSept();
      case UnoTextPackage.UNO_OLYPIQUE__CARTE2:
        return getCarte2();
      case UnoTextPackage.UNO_OLYPIQUE__VALEUR_CARTE:
        return getValeurCarte();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_OLYPIQUE__TRIBUNAL_POPULAIRE:
        setTribunalPopulaire((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE:
        setDistributionAleatoire((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__SENS_DEFINI:
        setSensDefini((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CHANGEMENT_DONNEUR:
        setChangementDonneur((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE:
        setVueDesCartesApres1erPose((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DONNEUR_PREMIEROSE:
        setDonneurPremierose((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__JEU_RAPIDE:
        setJeuRapide((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__INTERCEPTION:
        setInterception((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES:
        setDeuxCartesIdentiques((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DECISION_CARTE:
        setDecisionCarte((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__SURENCHERE:
        setSurenchere((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTEZERO:
        setCartezero((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE_SEPT:
        setCarteSept((Boolean)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE2:
        setCarte2((String)newValue);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__VALEUR_CARTE:
        setValeurCarte((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_OLYPIQUE__TRIBUNAL_POPULAIRE:
        setTribunalPopulaire(TRIBUNAL_POPULAIRE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE:
        setDistributionAleatoire(DISTRIBUTION_ALEATOIRE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__SENS_DEFINI:
        setSensDefini(SENS_DEFINI_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CHANGEMENT_DONNEUR:
        setChangementDonneur(CHANGEMENT_DONNEUR_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE:
        setVueDesCartesApres1erPose(VUE_DES_CARTES_APRES1ER_POSE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DONNEUR_PREMIEROSE:
        setDonneurPremierose(DONNEUR_PREMIEROSE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__JEU_RAPIDE:
        setJeuRapide(JEU_RAPIDE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__INTERCEPTION:
        setInterception(INTERCEPTION_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES:
        setDeuxCartesIdentiques(DEUX_CARTES_IDENTIQUES_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__DECISION_CARTE:
        setDecisionCarte(DECISION_CARTE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__SURENCHERE:
        setSurenchere(SURENCHERE_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTEZERO:
        setCartezero(CARTEZERO_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE_SEPT:
        setCarteSept(CARTE_SEPT_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE2:
        setCarte2(CARTE2_EDEFAULT);
        return;
      case UnoTextPackage.UNO_OLYPIQUE__VALEUR_CARTE:
        setValeurCarte(VALEUR_CARTE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UnoTextPackage.UNO_OLYPIQUE__TRIBUNAL_POPULAIRE:
        return TRIBUNAL_POPULAIRE_EDEFAULT == null ? tribunalPopulaire != null : !TRIBUNAL_POPULAIRE_EDEFAULT.equals(tribunalPopulaire);
      case UnoTextPackage.UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE:
        return DISTRIBUTION_ALEATOIRE_EDEFAULT == null ? distributionAleatoire != null : !DISTRIBUTION_ALEATOIRE_EDEFAULT.equals(distributionAleatoire);
      case UnoTextPackage.UNO_OLYPIQUE__SENS_DEFINI:
        return SENS_DEFINI_EDEFAULT == null ? sensDefini != null : !SENS_DEFINI_EDEFAULT.equals(sensDefini);
      case UnoTextPackage.UNO_OLYPIQUE__CHANGEMENT_DONNEUR:
        return CHANGEMENT_DONNEUR_EDEFAULT == null ? changementDonneur != null : !CHANGEMENT_DONNEUR_EDEFAULT.equals(changementDonneur);
      case UnoTextPackage.UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE:
        return VUE_DES_CARTES_APRES1ER_POSE_EDEFAULT == null ? vueDesCartesApres1erPose != null : !VUE_DES_CARTES_APRES1ER_POSE_EDEFAULT.equals(vueDesCartesApres1erPose);
      case UnoTextPackage.UNO_OLYPIQUE__DONNEUR_PREMIEROSE:
        return DONNEUR_PREMIEROSE_EDEFAULT == null ? donneurPremierose != null : !DONNEUR_PREMIEROSE_EDEFAULT.equals(donneurPremierose);
      case UnoTextPackage.UNO_OLYPIQUE__JEU_RAPIDE:
        return JEU_RAPIDE_EDEFAULT == null ? jeuRapide != null : !JEU_RAPIDE_EDEFAULT.equals(jeuRapide);
      case UnoTextPackage.UNO_OLYPIQUE__INTERCEPTION:
        return INTERCEPTION_EDEFAULT == null ? interception != null : !INTERCEPTION_EDEFAULT.equals(interception);
      case UnoTextPackage.UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES:
        return DEUX_CARTES_IDENTIQUES_EDEFAULT == null ? deuxCartesIdentiques != null : !DEUX_CARTES_IDENTIQUES_EDEFAULT.equals(deuxCartesIdentiques);
      case UnoTextPackage.UNO_OLYPIQUE__DECISION_CARTE:
        return DECISION_CARTE_EDEFAULT == null ? decisionCarte != null : !DECISION_CARTE_EDEFAULT.equals(decisionCarte);
      case UnoTextPackage.UNO_OLYPIQUE__SURENCHERE:
        return SURENCHERE_EDEFAULT == null ? surenchere != null : !SURENCHERE_EDEFAULT.equals(surenchere);
      case UnoTextPackage.UNO_OLYPIQUE__CARTEZERO:
        return cartezero != CARTEZERO_EDEFAULT;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE_SEPT:
        return carteSept != CARTE_SEPT_EDEFAULT;
      case UnoTextPackage.UNO_OLYPIQUE__CARTE2:
        return CARTE2_EDEFAULT == null ? carte2 != null : !CARTE2_EDEFAULT.equals(carte2);
      case UnoTextPackage.UNO_OLYPIQUE__VALEUR_CARTE:
        return VALEUR_CARTE_EDEFAULT == null ? valeurCarte != null : !VALEUR_CARTE_EDEFAULT.equals(valeurCarte);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (TribunalPopulaire: ");
    result.append(tribunalPopulaire);
    result.append(", DistributionAleatoire: ");
    result.append(distributionAleatoire);
    result.append(", SensDefini: ");
    result.append(sensDefini);
    result.append(", ChangementDonneur: ");
    result.append(changementDonneur);
    result.append(", VueDesCartesApres1erPose: ");
    result.append(vueDesCartesApres1erPose);
    result.append(", DonneurPremierose: ");
    result.append(donneurPremierose);
    result.append(", JeuRapide: ");
    result.append(jeuRapide);
    result.append(", Interception: ");
    result.append(interception);
    result.append(", DeuxCartesIdentiques: ");
    result.append(deuxCartesIdentiques);
    result.append(", DecisionCarte: ");
    result.append(decisionCarte);
    result.append(", Surenchere: ");
    result.append(surenchere);
    result.append(", cartezero: ");
    result.append(cartezero);
    result.append(", CarteSept: ");
    result.append(carteSept);
    result.append(", Carte2: ");
    result.append(carte2);
    result.append(", ValeurCarte: ");
    result.append(valeurCarte);
    result.append(')');
    return result.toString();
  }

} //UnoOlypiqueImpl
