/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.unotext.unoText.CarteIdentique;
import org.xtext.example.unotext.unoText.CumulAjout;
import org.xtext.example.unotext.unoText.Uno;
import org.xtext.example.unotext.unoText.UnoOlypique;
import org.xtext.example.unotext.unoText.UnoTextFactory;
import org.xtext.example.unotext.unoText.UnoTextPackage;
import org.xtext.example.unotext.unoText.UnoWizz;
import org.xtext.example.unotext.unoText.Uno_Classic;
import org.xtext.example.unotext.unoText.Uno_Rule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UnoTextPackageImpl extends EPackageImpl implements UnoTextPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uno_RuleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uno_ClassicEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass carteIdentiqueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cumulAjoutEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unoOlypiqueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass unoWizzEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private UnoTextPackageImpl()
  {
    super(eNS_URI, UnoTextFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link UnoTextPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static UnoTextPackage init()
  {
    if (isInited) return (UnoTextPackage)EPackage.Registry.INSTANCE.getEPackage(UnoTextPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredUnoTextPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    UnoTextPackageImpl theUnoTextPackage = registeredUnoTextPackage instanceof UnoTextPackageImpl ? (UnoTextPackageImpl)registeredUnoTextPackage : new UnoTextPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theUnoTextPackage.createPackageContents();

    // Initialize created meta-data
    theUnoTextPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theUnoTextPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(UnoTextPackage.eNS_URI, theUnoTextPackage);
    return theUnoTextPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUno()
  {
    return unoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUno_Uno()
  {
    return (EReference)unoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_NombreJoueur()
  {
    return (EAttribute)unoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUno_Rule()
  {
    return uno_RuleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUno_Classic()
  {
    return uno_ClassicEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_UnoChallenge()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_Carte0_7()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_CarteIdentique()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_CumulAjout()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_Suite()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_Pioche()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_More4()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_TempsLimite()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_MauvaiseCarte()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_Equipe()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_CarteVisibles()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_FinManche()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_ThreeHands()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_ThreePiles()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_SpecialCard()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUno_Classic_GameOver()
  {
    return (EAttribute)uno_ClassicEClass.getEStructuralFeatures().get(15);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCarteIdentique()
  {
    return carteIdentiqueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCarteIdentique_AvecCouleur()
  {
    return (EAttribute)carteIdentiqueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCumulAjout()
  {
    return cumulAjoutEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCumulAjout_Plus2()
  {
    return (EAttribute)cumulAjoutEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCumulAjout_Plus4()
  {
    return (EAttribute)cumulAjoutEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUnoOlypique()
  {
    return unoOlypiqueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_TribunalPopulaire()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_DistributionAleatoire()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_SensDefini()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_ChangementDonneur()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_VueDesCartesApres1erPose()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_DonneurPremierose()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_JeuRapide()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_Interception()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_DeuxCartesIdentiques()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_DecisionCarte()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_Surenchere()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_Cartezero()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_CarteSept()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_Carte2()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoOlypique_ValeurCarte()
  {
    return (EAttribute)unoOlypiqueEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUnoWizz()
  {
    return unoWizzEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoWizz_PresquUno()
  {
    return (EAttribute)unoWizzEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoWizz_ChiffreMoins()
  {
    return (EAttribute)unoWizzEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoWizz_CouleurMoins()
  {
    return (EAttribute)unoWizzEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUnoWizz_CarteRouge()
  {
    return (EAttribute)unoWizzEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UnoTextFactory getUnoTextFactory()
  {
    return (UnoTextFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    unoEClass = createEClass(UNO);
    createEReference(unoEClass, UNO__UNO);
    createEAttribute(unoEClass, UNO__NOMBRE_JOUEUR);

    uno_RuleEClass = createEClass(UNO_RULE);

    uno_ClassicEClass = createEClass(UNO_CLASSIC);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__UNO_CHALLENGE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__CARTE0_7);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__CARTE_IDENTIQUE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__CUMUL_AJOUT);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__SUITE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__PIOCHE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__MORE4);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__TEMPS_LIMITE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__MAUVAISE_CARTE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__EQUIPE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__CARTE_VISIBLES);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__FIN_MANCHE);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__THREE_HANDS);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__THREE_PILES);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__SPECIAL_CARD);
    createEAttribute(uno_ClassicEClass, UNO_CLASSIC__GAME_OVER);

    carteIdentiqueEClass = createEClass(CARTE_IDENTIQUE);
    createEAttribute(carteIdentiqueEClass, CARTE_IDENTIQUE__AVEC_COULEUR);

    cumulAjoutEClass = createEClass(CUMUL_AJOUT);
    createEAttribute(cumulAjoutEClass, CUMUL_AJOUT__PLUS2);
    createEAttribute(cumulAjoutEClass, CUMUL_AJOUT__PLUS4);

    unoOlypiqueEClass = createEClass(UNO_OLYPIQUE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__TRIBUNAL_POPULAIRE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__SENS_DEFINI);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__CHANGEMENT_DONNEUR);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__DONNEUR_PREMIEROSE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__JEU_RAPIDE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__INTERCEPTION);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__DECISION_CARTE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__SURENCHERE);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__CARTEZERO);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__CARTE_SEPT);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__CARTE2);
    createEAttribute(unoOlypiqueEClass, UNO_OLYPIQUE__VALEUR_CARTE);

    unoWizzEClass = createEClass(UNO_WIZZ);
    createEAttribute(unoWizzEClass, UNO_WIZZ__PRESQU_UNO);
    createEAttribute(unoWizzEClass, UNO_WIZZ__CHIFFRE_MOINS);
    createEAttribute(unoWizzEClass, UNO_WIZZ__COULEUR_MOINS);
    createEAttribute(unoWizzEClass, UNO_WIZZ__CARTE_ROUGE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    uno_ClassicEClass.getESuperTypes().add(this.getUno_Rule());
    unoOlypiqueEClass.getESuperTypes().add(this.getUno_Rule());
    unoWizzEClass.getESuperTypes().add(this.getUno_Rule());

    // Initialize classes and features; add operations and parameters
    initEClass(unoEClass, Uno.class, "Uno", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUno_Uno(), this.getUno_Rule(), null, "uno", null, 0, -1, Uno.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_NombreJoueur(), ecorePackage.getEString(), "nombreJoueur", null, 0, -1, Uno.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uno_RuleEClass, Uno_Rule.class, "Uno_Rule", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uno_ClassicEClass, Uno_Classic.class, "Uno_Classic", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUno_Classic_UnoChallenge(), ecorePackage.getEBoolean(), "unoChallenge", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_Carte0_7(), ecorePackage.getEBoolean(), "carte0_7", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_CarteIdentique(), ecorePackage.getEBoolean(), "carteIdentique", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_CumulAjout(), ecorePackage.getEBoolean(), "cumulAjout", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_Suite(), ecorePackage.getEBoolean(), "suite", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_Pioche(), ecorePackage.getEBoolean(), "pioche", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_More4(), ecorePackage.getEBoolean(), "more4", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_TempsLimite(), ecorePackage.getEBoolean(), "tempsLimite", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_MauvaiseCarte(), ecorePackage.getEBoolean(), "mauvaiseCarte", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_Equipe(), ecorePackage.getEBoolean(), "equipe", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_CarteVisibles(), ecorePackage.getEBoolean(), "carteVisibles", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_FinManche(), ecorePackage.getEBoolean(), "finManche", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_ThreeHands(), ecorePackage.getEBoolean(), "threeHands", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_ThreePiles(), ecorePackage.getEBoolean(), "threePiles", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_SpecialCard(), ecorePackage.getEBoolean(), "specialCard", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUno_Classic_GameOver(), ecorePackage.getEString(), "gameOver", null, 0, 1, Uno_Classic.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(carteIdentiqueEClass, CarteIdentique.class, "CarteIdentique", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCarteIdentique_AvecCouleur(), ecorePackage.getEBoolean(), "AvecCouleur", null, 0, 1, CarteIdentique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cumulAjoutEClass, CumulAjout.class, "CumulAjout", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCumulAjout_Plus2(), ecorePackage.getEBoolean(), "plus2", null, 0, 1, CumulAjout.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCumulAjout_Plus4(), ecorePackage.getEBoolean(), "plus4", null, 0, 1, CumulAjout.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(unoOlypiqueEClass, UnoOlypique.class, "UnoOlypique", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnoOlypique_TribunalPopulaire(), ecorePackage.getEString(), "TribunalPopulaire", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_DistributionAleatoire(), ecorePackage.getEString(), "DistributionAleatoire", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_SensDefini(), ecorePackage.getEString(), "SensDefini", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_ChangementDonneur(), ecorePackage.getEString(), "ChangementDonneur", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_VueDesCartesApres1erPose(), ecorePackage.getEString(), "VueDesCartesApres1erPose", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_DonneurPremierose(), ecorePackage.getEString(), "DonneurPremierose", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_JeuRapide(), ecorePackage.getEString(), "JeuRapide", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_Interception(), ecorePackage.getEString(), "Interception", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_DeuxCartesIdentiques(), ecorePackage.getEString(), "DeuxCartesIdentiques", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_DecisionCarte(), ecorePackage.getEString(), "DecisionCarte", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_Surenchere(), ecorePackage.getEString(), "Surenchere", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_Cartezero(), ecorePackage.getEBoolean(), "cartezero", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_CarteSept(), ecorePackage.getEBoolean(), "CarteSept", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_Carte2(), ecorePackage.getEString(), "Carte2", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoOlypique_ValeurCarte(), ecorePackage.getEString(), "ValeurCarte", null, 0, 1, UnoOlypique.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(unoWizzEClass, UnoWizz.class, "UnoWizz", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUnoWizz_PresquUno(), ecorePackage.getEString(), "presquUno", null, 0, 1, UnoWizz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoWizz_ChiffreMoins(), ecorePackage.getEString(), "chiffreMoins", null, 0, 1, UnoWizz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoWizz_CouleurMoins(), ecorePackage.getEString(), "couleurMoins", null, 0, 1, UnoWizz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUnoWizz_CarteRouge(), ecorePackage.getEString(), "carteRouge", null, 0, 1, UnoWizz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //UnoTextPackageImpl
