/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UnoTextUiModule extends AbstractUnoTextUiModule {

	public UnoTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
