/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.unotext.UnoTextRuntimeModule;
import org.xtext.example.unotext.UnoTextStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class UnoTextIdeSetup extends UnoTextStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UnoTextRuntimeModule(), new UnoTextIdeModule()));
	}
	
}
