/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Carte Identique</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.CarteIdentique#isAvecCouleur <em>Avec Couleur</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getCarteIdentique()
 * @model
 * @generated
 */
public interface CarteIdentique extends EObject
{
  /**
   * Returns the value of the '<em><b>Avec Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Avec Couleur</em>' attribute.
   * @see #setAvecCouleur(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getCarteIdentique_AvecCouleur()
   * @model
   * @generated
   */
  boolean isAvecCouleur();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.CarteIdentique#isAvecCouleur <em>Avec Couleur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Avec Couleur</em>' attribute.
   * @see #isAvecCouleur()
   * @generated
   */
  void setAvecCouleur(boolean value);

} // CarteIdentique
