/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cumul Ajout</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus2 <em>Plus2</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus4 <em>Plus4</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getCumulAjout()
 * @model
 * @generated
 */
public interface CumulAjout extends EObject
{
  /**
   * Returns the value of the '<em><b>Plus2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus2</em>' attribute.
   * @see #setPlus2(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getCumulAjout_Plus2()
   * @model
   * @generated
   */
  boolean isPlus2();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus2 <em>Plus2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus2</em>' attribute.
   * @see #isPlus2()
   * @generated
   */
  void setPlus2(boolean value);

  /**
   * Returns the value of the '<em><b>Plus4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus4</em>' attribute.
   * @see #setPlus4(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getCumulAjout_Plus4()
   * @model
   * @generated
   */
  boolean isPlus4();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus4 <em>Plus4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus4</em>' attribute.
   * @see #isPlus4()
   * @generated
   */
  void setPlus4(boolean value);

} // CumulAjout
