/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno#getUno <em>Uno</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno#getNombreJoueur <em>Nombre Joueur</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno()
 * @model
 * @generated
 */
public interface Uno extends EObject
{
  /**
   * Returns the value of the '<em><b>Uno</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.unotext.unoText.Uno_Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uno</em>' containment reference list.
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Uno()
   * @model containment="true"
   * @generated
   */
  EList<Uno_Rule> getUno();

  /**
   * Returns the value of the '<em><b>Nombre Joueur</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre Joueur</em>' attribute list.
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_NombreJoueur()
   * @model unique="false"
   * @generated
   */
  EList<String> getNombreJoueur();

} // Uno
