/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Classic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isUnoChallenge <em>Uno Challenge</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarte0_7 <em>Carte0 7</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteIdentique <em>Carte Identique</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isCumulAjout <em>Cumul Ajout</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isSuite <em>Suite</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isPioche <em>Pioche</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isMore4 <em>More4</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isTempsLimite <em>Temps Limite</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isMauvaiseCarte <em>Mauvaise Carte</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isEquipe <em>Equipe</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteVisibles <em>Carte Visibles</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isFinManche <em>Fin Manche</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreeHands <em>Three Hands</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreePiles <em>Three Piles</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#isSpecialCard <em>Special Card</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.Uno_Classic#getGameOver <em>Game Over</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic()
 * @model
 * @generated
 */
public interface Uno_Classic extends Uno_Rule
{
  /**
   * Returns the value of the '<em><b>Uno Challenge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uno Challenge</em>' attribute.
   * @see #setUnoChallenge(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_UnoChallenge()
   * @model
   * @generated
   */
  boolean isUnoChallenge();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isUnoChallenge <em>Uno Challenge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uno Challenge</em>' attribute.
   * @see #isUnoChallenge()
   * @generated
   */
  void setUnoChallenge(boolean value);

  /**
   * Returns the value of the '<em><b>Carte0 7</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte0 7</em>' attribute.
   * @see #setCarte0_7(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_Carte0_7()
   * @model
   * @generated
   */
  boolean isCarte0_7();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarte0_7 <em>Carte0 7</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte0 7</em>' attribute.
   * @see #isCarte0_7()
   * @generated
   */
  void setCarte0_7(boolean value);

  /**
   * Returns the value of the '<em><b>Carte Identique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Identique</em>' attribute.
   * @see #setCarteIdentique(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_CarteIdentique()
   * @model
   * @generated
   */
  boolean isCarteIdentique();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteIdentique <em>Carte Identique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Identique</em>' attribute.
   * @see #isCarteIdentique()
   * @generated
   */
  void setCarteIdentique(boolean value);

  /**
   * Returns the value of the '<em><b>Cumul Ajout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul Ajout</em>' attribute.
   * @see #setCumulAjout(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_CumulAjout()
   * @model
   * @generated
   */
  boolean isCumulAjout();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCumulAjout <em>Cumul Ajout</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul Ajout</em>' attribute.
   * @see #isCumulAjout()
   * @generated
   */
  void setCumulAjout(boolean value);

  /**
   * Returns the value of the '<em><b>Suite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suite</em>' attribute.
   * @see #setSuite(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_Suite()
   * @model
   * @generated
   */
  boolean isSuite();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isSuite <em>Suite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Suite</em>' attribute.
   * @see #isSuite()
   * @generated
   */
  void setSuite(boolean value);

  /**
   * Returns the value of the '<em><b>Pioche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pioche</em>' attribute.
   * @see #setPioche(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_Pioche()
   * @model
   * @generated
   */
  boolean isPioche();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isPioche <em>Pioche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pioche</em>' attribute.
   * @see #isPioche()
   * @generated
   */
  void setPioche(boolean value);

  /**
   * Returns the value of the '<em><b>More4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>More4</em>' attribute.
   * @see #setMore4(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_More4()
   * @model
   * @generated
   */
  boolean isMore4();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isMore4 <em>More4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>More4</em>' attribute.
   * @see #isMore4()
   * @generated
   */
  void setMore4(boolean value);

  /**
   * Returns the value of the '<em><b>Temps Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temps Limite</em>' attribute.
   * @see #setTempsLimite(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_TempsLimite()
   * @model
   * @generated
   */
  boolean isTempsLimite();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isTempsLimite <em>Temps Limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temps Limite</em>' attribute.
   * @see #isTempsLimite()
   * @generated
   */
  void setTempsLimite(boolean value);

  /**
   * Returns the value of the '<em><b>Mauvaise Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mauvaise Carte</em>' attribute.
   * @see #setMauvaiseCarte(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_MauvaiseCarte()
   * @model
   * @generated
   */
  boolean isMauvaiseCarte();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isMauvaiseCarte <em>Mauvaise Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mauvaise Carte</em>' attribute.
   * @see #isMauvaiseCarte()
   * @generated
   */
  void setMauvaiseCarte(boolean value);

  /**
   * Returns the value of the '<em><b>Equipe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equipe</em>' attribute.
   * @see #setEquipe(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_Equipe()
   * @model
   * @generated
   */
  boolean isEquipe();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isEquipe <em>Equipe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equipe</em>' attribute.
   * @see #isEquipe()
   * @generated
   */
  void setEquipe(boolean value);

  /**
   * Returns the value of the '<em><b>Carte Visibles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Visibles</em>' attribute.
   * @see #setCarteVisibles(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_CarteVisibles()
   * @model
   * @generated
   */
  boolean isCarteVisibles();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteVisibles <em>Carte Visibles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Visibles</em>' attribute.
   * @see #isCarteVisibles()
   * @generated
   */
  void setCarteVisibles(boolean value);

  /**
   * Returns the value of the '<em><b>Fin Manche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin Manche</em>' attribute.
   * @see #setFinManche(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_FinManche()
   * @model
   * @generated
   */
  boolean isFinManche();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isFinManche <em>Fin Manche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin Manche</em>' attribute.
   * @see #isFinManche()
   * @generated
   */
  void setFinManche(boolean value);

  /**
   * Returns the value of the '<em><b>Three Hands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Three Hands</em>' attribute.
   * @see #setThreeHands(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_ThreeHands()
   * @model
   * @generated
   */
  boolean isThreeHands();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreeHands <em>Three Hands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Three Hands</em>' attribute.
   * @see #isThreeHands()
   * @generated
   */
  void setThreeHands(boolean value);

  /**
   * Returns the value of the '<em><b>Three Piles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Three Piles</em>' attribute.
   * @see #setThreePiles(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_ThreePiles()
   * @model
   * @generated
   */
  boolean isThreePiles();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreePiles <em>Three Piles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Three Piles</em>' attribute.
   * @see #isThreePiles()
   * @generated
   */
  void setThreePiles(boolean value);

  /**
   * Returns the value of the '<em><b>Special Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Special Card</em>' attribute.
   * @see #setSpecialCard(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_SpecialCard()
   * @model
   * @generated
   */
  boolean isSpecialCard();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#isSpecialCard <em>Special Card</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Special Card</em>' attribute.
   * @see #isSpecialCard()
   * @generated
   */
  void setSpecialCard(boolean value);

  /**
   * Returns the value of the '<em><b>Game Over</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game Over</em>' attribute.
   * @see #setGameOver(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Classic_GameOver()
   * @model
   * @generated
   */
  String getGameOver();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.Uno_Classic#getGameOver <em>Game Over</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Game Over</em>' attribute.
   * @see #getGameOver()
   * @generated
   */
  void setGameOver(String value);

} // Uno_Classic
