/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUno_Rule()
 * @model
 * @generated
 */
public interface Uno_Rule extends EObject
{
} // Uno_Rule
