/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Olypique</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getTribunalPopulaire <em>Tribunal Populaire</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getDistributionAleatoire <em>Distribution Aleatoire</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getSensDefini <em>Sens Defini</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getChangementDonneur <em>Changement Donneur</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getVueDesCartesApres1erPose <em>Vue Des Cartes Apres1er Pose</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getDonneurPremierose <em>Donneur Premierose</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getJeuRapide <em>Jeu Rapide</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getInterception <em>Interception</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getDeuxCartesIdentiques <em>Deux Cartes Identiques</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getDecisionCarte <em>Decision Carte</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getSurenchere <em>Surenchere</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#isCartezero <em>Cartezero</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#isCarteSept <em>Carte Sept</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getCarte2 <em>Carte2</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoOlypique#getValeurCarte <em>Valeur Carte</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique()
 * @model
 * @generated
 */
public interface UnoOlypique extends Uno_Rule
{
  /**
   * Returns the value of the '<em><b>Tribunal Populaire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tribunal Populaire</em>' attribute.
   * @see #setTribunalPopulaire(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_TribunalPopulaire()
   * @model
   * @generated
   */
  String getTribunalPopulaire();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getTribunalPopulaire <em>Tribunal Populaire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tribunal Populaire</em>' attribute.
   * @see #getTribunalPopulaire()
   * @generated
   */
  void setTribunalPopulaire(String value);

  /**
   * Returns the value of the '<em><b>Distribution Aleatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distribution Aleatoire</em>' attribute.
   * @see #setDistributionAleatoire(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_DistributionAleatoire()
   * @model
   * @generated
   */
  String getDistributionAleatoire();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDistributionAleatoire <em>Distribution Aleatoire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distribution Aleatoire</em>' attribute.
   * @see #getDistributionAleatoire()
   * @generated
   */
  void setDistributionAleatoire(String value);

  /**
   * Returns the value of the '<em><b>Sens Defini</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sens Defini</em>' attribute.
   * @see #setSensDefini(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_SensDefini()
   * @model
   * @generated
   */
  String getSensDefini();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getSensDefini <em>Sens Defini</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sens Defini</em>' attribute.
   * @see #getSensDefini()
   * @generated
   */
  void setSensDefini(String value);

  /**
   * Returns the value of the '<em><b>Changement Donneur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Changement Donneur</em>' attribute.
   * @see #setChangementDonneur(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_ChangementDonneur()
   * @model
   * @generated
   */
  String getChangementDonneur();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getChangementDonneur <em>Changement Donneur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Changement Donneur</em>' attribute.
   * @see #getChangementDonneur()
   * @generated
   */
  void setChangementDonneur(String value);

  /**
   * Returns the value of the '<em><b>Vue Des Cartes Apres1er Pose</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vue Des Cartes Apres1er Pose</em>' attribute.
   * @see #setVueDesCartesApres1erPose(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_VueDesCartesApres1erPose()
   * @model
   * @generated
   */
  String getVueDesCartesApres1erPose();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getVueDesCartesApres1erPose <em>Vue Des Cartes Apres1er Pose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vue Des Cartes Apres1er Pose</em>' attribute.
   * @see #getVueDesCartesApres1erPose()
   * @generated
   */
  void setVueDesCartesApres1erPose(String value);

  /**
   * Returns the value of the '<em><b>Donneur Premierose</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Donneur Premierose</em>' attribute.
   * @see #setDonneurPremierose(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_DonneurPremierose()
   * @model
   * @generated
   */
  String getDonneurPremierose();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDonneurPremierose <em>Donneur Premierose</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Donneur Premierose</em>' attribute.
   * @see #getDonneurPremierose()
   * @generated
   */
  void setDonneurPremierose(String value);

  /**
   * Returns the value of the '<em><b>Jeu Rapide</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jeu Rapide</em>' attribute.
   * @see #setJeuRapide(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_JeuRapide()
   * @model
   * @generated
   */
  String getJeuRapide();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getJeuRapide <em>Jeu Rapide</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Jeu Rapide</em>' attribute.
   * @see #getJeuRapide()
   * @generated
   */
  void setJeuRapide(String value);

  /**
   * Returns the value of the '<em><b>Interception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Interception</em>' attribute.
   * @see #setInterception(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_Interception()
   * @model
   * @generated
   */
  String getInterception();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getInterception <em>Interception</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Interception</em>' attribute.
   * @see #getInterception()
   * @generated
   */
  void setInterception(String value);

  /**
   * Returns the value of the '<em><b>Deux Cartes Identiques</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deux Cartes Identiques</em>' attribute.
   * @see #setDeuxCartesIdentiques(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_DeuxCartesIdentiques()
   * @model
   * @generated
   */
  String getDeuxCartesIdentiques();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDeuxCartesIdentiques <em>Deux Cartes Identiques</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deux Cartes Identiques</em>' attribute.
   * @see #getDeuxCartesIdentiques()
   * @generated
   */
  void setDeuxCartesIdentiques(String value);

  /**
   * Returns the value of the '<em><b>Decision Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Carte</em>' attribute.
   * @see #setDecisionCarte(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_DecisionCarte()
   * @model
   * @generated
   */
  String getDecisionCarte();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDecisionCarte <em>Decision Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Carte</em>' attribute.
   * @see #getDecisionCarte()
   * @generated
   */
  void setDecisionCarte(String value);

  /**
   * Returns the value of the '<em><b>Surenchere</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surenchere</em>' attribute.
   * @see #setSurenchere(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_Surenchere()
   * @model
   * @generated
   */
  String getSurenchere();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getSurenchere <em>Surenchere</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surenchere</em>' attribute.
   * @see #getSurenchere()
   * @generated
   */
  void setSurenchere(String value);

  /**
   * Returns the value of the '<em><b>Cartezero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartezero</em>' attribute.
   * @see #setCartezero(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_Cartezero()
   * @model
   * @generated
   */
  boolean isCartezero();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#isCartezero <em>Cartezero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartezero</em>' attribute.
   * @see #isCartezero()
   * @generated
   */
  void setCartezero(boolean value);

  /**
   * Returns the value of the '<em><b>Carte Sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Sept</em>' attribute.
   * @see #setCarteSept(boolean)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_CarteSept()
   * @model
   * @generated
   */
  boolean isCarteSept();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#isCarteSept <em>Carte Sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Sept</em>' attribute.
   * @see #isCarteSept()
   * @generated
   */
  void setCarteSept(boolean value);

  /**
   * Returns the value of the '<em><b>Carte2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte2</em>' attribute.
   * @see #setCarte2(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_Carte2()
   * @model
   * @generated
   */
  String getCarte2();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getCarte2 <em>Carte2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte2</em>' attribute.
   * @see #getCarte2()
   * @generated
   */
  void setCarte2(String value);

  /**
   * Returns the value of the '<em><b>Valeur Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valeur Carte</em>' attribute.
   * @see #setValeurCarte(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoOlypique_ValeurCarte()
   * @model
   * @generated
   */
  String getValeurCarte();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoOlypique#getValeurCarte <em>Valeur Carte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valeur Carte</em>' attribute.
   * @see #getValeurCarte()
   * @generated
   */
  void setValeurCarte(String value);

} // UnoOlypique
