/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.unotext.unoText.UnoTextFactory
 * @model kind="package"
 * @generated
 */
public interface UnoTextPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "unoText";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/unotext/UnoText";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "unoText";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnoTextPackage eINSTANCE = org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.UnoImpl <em>Uno</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.UnoImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno()
   * @generated
   */
  int UNO = 0;

  /**
   * The feature id for the '<em><b>Uno</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO__UNO = 0;

  /**
   * The feature id for the '<em><b>Nombre Joueur</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO__NOMBRE_JOUEUR = 1;

  /**
   * The number of structural features of the '<em>Uno</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.Uno_RuleImpl <em>Uno Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.Uno_RuleImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno_Rule()
   * @generated
   */
  int UNO_RULE = 1;

  /**
   * The number of structural features of the '<em>Uno Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl <em>Uno Classic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno_Classic()
   * @generated
   */
  int UNO_CLASSIC = 2;

  /**
   * The feature id for the '<em><b>Uno Challenge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__UNO_CHALLENGE = UNO_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Carte0 7</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__CARTE0_7 = UNO_RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Carte Identique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__CARTE_IDENTIQUE = UNO_RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Cumul Ajout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__CUMUL_AJOUT = UNO_RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Suite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__SUITE = UNO_RULE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Pioche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__PIOCHE = UNO_RULE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>More4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__MORE4 = UNO_RULE_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Temps Limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__TEMPS_LIMITE = UNO_RULE_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Mauvaise Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__MAUVAISE_CARTE = UNO_RULE_FEATURE_COUNT + 8;

  /**
   * The feature id for the '<em><b>Equipe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__EQUIPE = UNO_RULE_FEATURE_COUNT + 9;

  /**
   * The feature id for the '<em><b>Carte Visibles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__CARTE_VISIBLES = UNO_RULE_FEATURE_COUNT + 10;

  /**
   * The feature id for the '<em><b>Fin Manche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__FIN_MANCHE = UNO_RULE_FEATURE_COUNT + 11;

  /**
   * The feature id for the '<em><b>Three Hands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__THREE_HANDS = UNO_RULE_FEATURE_COUNT + 12;

  /**
   * The feature id for the '<em><b>Three Piles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__THREE_PILES = UNO_RULE_FEATURE_COUNT + 13;

  /**
   * The feature id for the '<em><b>Special Card</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__SPECIAL_CARD = UNO_RULE_FEATURE_COUNT + 14;

  /**
   * The feature id for the '<em><b>Game Over</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC__GAME_OVER = UNO_RULE_FEATURE_COUNT + 15;

  /**
   * The number of structural features of the '<em>Uno Classic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_CLASSIC_FEATURE_COUNT = UNO_RULE_FEATURE_COUNT + 16;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.CarteIdentiqueImpl <em>Carte Identique</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.CarteIdentiqueImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getCarteIdentique()
   * @generated
   */
  int CARTE_IDENTIQUE = 3;

  /**
   * The feature id for the '<em><b>Avec Couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_IDENTIQUE__AVEC_COULEUR = 0;

  /**
   * The number of structural features of the '<em>Carte Identique</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTE_IDENTIQUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.CumulAjoutImpl <em>Cumul Ajout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.CumulAjoutImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getCumulAjout()
   * @generated
   */
  int CUMUL_AJOUT = 4;

  /**
   * The feature id for the '<em><b>Plus2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL_AJOUT__PLUS2 = 0;

  /**
   * The feature id for the '<em><b>Plus4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL_AJOUT__PLUS4 = 1;

  /**
   * The number of structural features of the '<em>Cumul Ajout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL_AJOUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl <em>Uno Olypique</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUnoOlypique()
   * @generated
   */
  int UNO_OLYPIQUE = 5;

  /**
   * The feature id for the '<em><b>Tribunal Populaire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__TRIBUNAL_POPULAIRE = UNO_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Distribution Aleatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE = UNO_RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sens Defini</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__SENS_DEFINI = UNO_RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Changement Donneur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__CHANGEMENT_DONNEUR = UNO_RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Vue Des Cartes Apres1er Pose</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE = UNO_RULE_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Donneur Premierose</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__DONNEUR_PREMIEROSE = UNO_RULE_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Jeu Rapide</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__JEU_RAPIDE = UNO_RULE_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Interception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__INTERCEPTION = UNO_RULE_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Deux Cartes Identiques</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES = UNO_RULE_FEATURE_COUNT + 8;

  /**
   * The feature id for the '<em><b>Decision Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__DECISION_CARTE = UNO_RULE_FEATURE_COUNT + 9;

  /**
   * The feature id for the '<em><b>Surenchere</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__SURENCHERE = UNO_RULE_FEATURE_COUNT + 10;

  /**
   * The feature id for the '<em><b>Cartezero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__CARTEZERO = UNO_RULE_FEATURE_COUNT + 11;

  /**
   * The feature id for the '<em><b>Carte Sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__CARTE_SEPT = UNO_RULE_FEATURE_COUNT + 12;

  /**
   * The feature id for the '<em><b>Carte2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__CARTE2 = UNO_RULE_FEATURE_COUNT + 13;

  /**
   * The feature id for the '<em><b>Valeur Carte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE__VALEUR_CARTE = UNO_RULE_FEATURE_COUNT + 14;

  /**
   * The number of structural features of the '<em>Uno Olypique</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_OLYPIQUE_FEATURE_COUNT = UNO_RULE_FEATURE_COUNT + 15;

  /**
   * The meta object id for the '{@link org.xtext.example.unotext.unoText.impl.UnoWizzImpl <em>Uno Wizz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.unotext.unoText.impl.UnoWizzImpl
   * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUnoWizz()
   * @generated
   */
  int UNO_WIZZ = 6;

  /**
   * The feature id for the '<em><b>Presqu Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_WIZZ__PRESQU_UNO = UNO_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Chiffre Moins</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_WIZZ__CHIFFRE_MOINS = UNO_RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Couleur Moins</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_WIZZ__COULEUR_MOINS = UNO_RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Carte Rouge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_WIZZ__CARTE_ROUGE = UNO_RULE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Uno Wizz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_WIZZ_FEATURE_COUNT = UNO_RULE_FEATURE_COUNT + 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.Uno <em>Uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno</em>'.
   * @see org.xtext.example.unotext.unoText.Uno
   * @generated
   */
  EClass getUno();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.unotext.unoText.Uno#getUno <em>Uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Uno</em>'.
   * @see org.xtext.example.unotext.unoText.Uno#getUno()
   * @see #getUno()
   * @generated
   */
  EReference getUno_Uno();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.unotext.unoText.Uno#getNombreJoueur <em>Nombre Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Nombre Joueur</em>'.
   * @see org.xtext.example.unotext.unoText.Uno#getNombreJoueur()
   * @see #getUno()
   * @generated
   */
  EAttribute getUno_NombreJoueur();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.Uno_Rule <em>Uno Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Rule</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Rule
   * @generated
   */
  EClass getUno_Rule();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.Uno_Classic <em>Uno Classic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Classic</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic
   * @generated
   */
  EClass getUno_Classic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isUnoChallenge <em>Uno Challenge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uno Challenge</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isUnoChallenge()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_UnoChallenge();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarte0_7 <em>Carte0 7</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte0 7</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isCarte0_7()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_Carte0_7();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteIdentique <em>Carte Identique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Identique</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isCarteIdentique()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_CarteIdentique();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCumulAjout <em>Cumul Ajout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul Ajout</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isCumulAjout()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_CumulAjout();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isSuite <em>Suite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suite</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isSuite()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_Suite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isPioche <em>Pioche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pioche</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isPioche()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_Pioche();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isMore4 <em>More4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>More4</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isMore4()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_More4();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isTempsLimite <em>Temps Limite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Temps Limite</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isTempsLimite()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_TempsLimite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isMauvaiseCarte <em>Mauvaise Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mauvaise Carte</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isMauvaiseCarte()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_MauvaiseCarte();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isEquipe <em>Equipe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Equipe</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isEquipe()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_Equipe();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isCarteVisibles <em>Carte Visibles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Visibles</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isCarteVisibles()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_CarteVisibles();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isFinManche <em>Fin Manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fin Manche</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isFinManche()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_FinManche();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreeHands <em>Three Hands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Three Hands</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isThreeHands()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_ThreeHands();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isThreePiles <em>Three Piles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Three Piles</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isThreePiles()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_ThreePiles();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#isSpecialCard <em>Special Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Special Card</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#isSpecialCard()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_SpecialCard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.Uno_Classic#getGameOver <em>Game Over</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Game Over</em>'.
   * @see org.xtext.example.unotext.unoText.Uno_Classic#getGameOver()
   * @see #getUno_Classic()
   * @generated
   */
  EAttribute getUno_Classic_GameOver();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.CarteIdentique <em>Carte Identique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carte Identique</em>'.
   * @see org.xtext.example.unotext.unoText.CarteIdentique
   * @generated
   */
  EClass getCarteIdentique();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.CarteIdentique#isAvecCouleur <em>Avec Couleur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Avec Couleur</em>'.
   * @see org.xtext.example.unotext.unoText.CarteIdentique#isAvecCouleur()
   * @see #getCarteIdentique()
   * @generated
   */
  EAttribute getCarteIdentique_AvecCouleur();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.CumulAjout <em>Cumul Ajout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cumul Ajout</em>'.
   * @see org.xtext.example.unotext.unoText.CumulAjout
   * @generated
   */
  EClass getCumulAjout();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus2 <em>Plus2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus2</em>'.
   * @see org.xtext.example.unotext.unoText.CumulAjout#isPlus2()
   * @see #getCumulAjout()
   * @generated
   */
  EAttribute getCumulAjout_Plus2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.CumulAjout#isPlus4 <em>Plus4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus4</em>'.
   * @see org.xtext.example.unotext.unoText.CumulAjout#isPlus4()
   * @see #getCumulAjout()
   * @generated
   */
  EAttribute getCumulAjout_Plus4();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.UnoOlypique <em>Uno Olypique</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Olypique</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique
   * @generated
   */
  EClass getUnoOlypique();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getTribunalPopulaire <em>Tribunal Populaire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tribunal Populaire</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getTribunalPopulaire()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_TribunalPopulaire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDistributionAleatoire <em>Distribution Aleatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distribution Aleatoire</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getDistributionAleatoire()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_DistributionAleatoire();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getSensDefini <em>Sens Defini</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sens Defini</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getSensDefini()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_SensDefini();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getChangementDonneur <em>Changement Donneur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Changement Donneur</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getChangementDonneur()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_ChangementDonneur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getVueDesCartesApres1erPose <em>Vue Des Cartes Apres1er Pose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vue Des Cartes Apres1er Pose</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getVueDesCartesApres1erPose()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_VueDesCartesApres1erPose();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDonneurPremierose <em>Donneur Premierose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Donneur Premierose</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getDonneurPremierose()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_DonneurPremierose();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getJeuRapide <em>Jeu Rapide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jeu Rapide</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getJeuRapide()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_JeuRapide();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getInterception <em>Interception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Interception</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getInterception()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_Interception();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDeuxCartesIdentiques <em>Deux Cartes Identiques</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Deux Cartes Identiques</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getDeuxCartesIdentiques()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_DeuxCartesIdentiques();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getDecisionCarte <em>Decision Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decision Carte</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getDecisionCarte()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_DecisionCarte();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getSurenchere <em>Surenchere</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Surenchere</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getSurenchere()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_Surenchere();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#isCartezero <em>Cartezero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cartezero</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#isCartezero()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_Cartezero();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#isCarteSept <em>Carte Sept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Sept</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#isCarteSept()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_CarteSept();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getCarte2 <em>Carte2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte2</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getCarte2()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_Carte2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoOlypique#getValeurCarte <em>Valeur Carte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur Carte</em>'.
   * @see org.xtext.example.unotext.unoText.UnoOlypique#getValeurCarte()
   * @see #getUnoOlypique()
   * @generated
   */
  EAttribute getUnoOlypique_ValeurCarte();

  /**
   * Returns the meta object for class '{@link org.xtext.example.unotext.unoText.UnoWizz <em>Uno Wizz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uno Wizz</em>'.
   * @see org.xtext.example.unotext.unoText.UnoWizz
   * @generated
   */
  EClass getUnoWizz();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoWizz#getPresquUno <em>Presqu Uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Presqu Uno</em>'.
   * @see org.xtext.example.unotext.unoText.UnoWizz#getPresquUno()
   * @see #getUnoWizz()
   * @generated
   */
  EAttribute getUnoWizz_PresquUno();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoWizz#getChiffreMoins <em>Chiffre Moins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chiffre Moins</em>'.
   * @see org.xtext.example.unotext.unoText.UnoWizz#getChiffreMoins()
   * @see #getUnoWizz()
   * @generated
   */
  EAttribute getUnoWizz_ChiffreMoins();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoWizz#getCouleurMoins <em>Couleur Moins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Couleur Moins</em>'.
   * @see org.xtext.example.unotext.unoText.UnoWizz#getCouleurMoins()
   * @see #getUnoWizz()
   * @generated
   */
  EAttribute getUnoWizz_CouleurMoins();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.unotext.unoText.UnoWizz#getCarteRouge <em>Carte Rouge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carte Rouge</em>'.
   * @see org.xtext.example.unotext.unoText.UnoWizz#getCarteRouge()
   * @see #getUnoWizz()
   * @generated
   */
  EAttribute getUnoWizz_CarteRouge();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UnoTextFactory getUnoTextFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.UnoImpl <em>Uno</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.UnoImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno()
     * @generated
     */
    EClass UNO = eINSTANCE.getUno();

    /**
     * The meta object literal for the '<em><b>Uno</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNO__UNO = eINSTANCE.getUno_Uno();

    /**
     * The meta object literal for the '<em><b>Nombre Joueur</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO__NOMBRE_JOUEUR = eINSTANCE.getUno_NombreJoueur();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.Uno_RuleImpl <em>Uno Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.Uno_RuleImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno_Rule()
     * @generated
     */
    EClass UNO_RULE = eINSTANCE.getUno_Rule();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl <em>Uno Classic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.Uno_ClassicImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUno_Classic()
     * @generated
     */
    EClass UNO_CLASSIC = eINSTANCE.getUno_Classic();

    /**
     * The meta object literal for the '<em><b>Uno Challenge</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__UNO_CHALLENGE = eINSTANCE.getUno_Classic_UnoChallenge();

    /**
     * The meta object literal for the '<em><b>Carte0 7</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__CARTE0_7 = eINSTANCE.getUno_Classic_Carte0_7();

    /**
     * The meta object literal for the '<em><b>Carte Identique</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__CARTE_IDENTIQUE = eINSTANCE.getUno_Classic_CarteIdentique();

    /**
     * The meta object literal for the '<em><b>Cumul Ajout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__CUMUL_AJOUT = eINSTANCE.getUno_Classic_CumulAjout();

    /**
     * The meta object literal for the '<em><b>Suite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__SUITE = eINSTANCE.getUno_Classic_Suite();

    /**
     * The meta object literal for the '<em><b>Pioche</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__PIOCHE = eINSTANCE.getUno_Classic_Pioche();

    /**
     * The meta object literal for the '<em><b>More4</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__MORE4 = eINSTANCE.getUno_Classic_More4();

    /**
     * The meta object literal for the '<em><b>Temps Limite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__TEMPS_LIMITE = eINSTANCE.getUno_Classic_TempsLimite();

    /**
     * The meta object literal for the '<em><b>Mauvaise Carte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__MAUVAISE_CARTE = eINSTANCE.getUno_Classic_MauvaiseCarte();

    /**
     * The meta object literal for the '<em><b>Equipe</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__EQUIPE = eINSTANCE.getUno_Classic_Equipe();

    /**
     * The meta object literal for the '<em><b>Carte Visibles</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__CARTE_VISIBLES = eINSTANCE.getUno_Classic_CarteVisibles();

    /**
     * The meta object literal for the '<em><b>Fin Manche</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__FIN_MANCHE = eINSTANCE.getUno_Classic_FinManche();

    /**
     * The meta object literal for the '<em><b>Three Hands</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__THREE_HANDS = eINSTANCE.getUno_Classic_ThreeHands();

    /**
     * The meta object literal for the '<em><b>Three Piles</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__THREE_PILES = eINSTANCE.getUno_Classic_ThreePiles();

    /**
     * The meta object literal for the '<em><b>Special Card</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__SPECIAL_CARD = eINSTANCE.getUno_Classic_SpecialCard();

    /**
     * The meta object literal for the '<em><b>Game Over</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_CLASSIC__GAME_OVER = eINSTANCE.getUno_Classic_GameOver();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.CarteIdentiqueImpl <em>Carte Identique</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.CarteIdentiqueImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getCarteIdentique()
     * @generated
     */
    EClass CARTE_IDENTIQUE = eINSTANCE.getCarteIdentique();

    /**
     * The meta object literal for the '<em><b>Avec Couleur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTE_IDENTIQUE__AVEC_COULEUR = eINSTANCE.getCarteIdentique_AvecCouleur();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.CumulAjoutImpl <em>Cumul Ajout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.CumulAjoutImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getCumulAjout()
     * @generated
     */
    EClass CUMUL_AJOUT = eINSTANCE.getCumulAjout();

    /**
     * The meta object literal for the '<em><b>Plus2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL_AJOUT__PLUS2 = eINSTANCE.getCumulAjout_Plus2();

    /**
     * The meta object literal for the '<em><b>Plus4</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL_AJOUT__PLUS4 = eINSTANCE.getCumulAjout_Plus4();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl <em>Uno Olypique</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.UnoOlypiqueImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUnoOlypique()
     * @generated
     */
    EClass UNO_OLYPIQUE = eINSTANCE.getUnoOlypique();

    /**
     * The meta object literal for the '<em><b>Tribunal Populaire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__TRIBUNAL_POPULAIRE = eINSTANCE.getUnoOlypique_TribunalPopulaire();

    /**
     * The meta object literal for the '<em><b>Distribution Aleatoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__DISTRIBUTION_ALEATOIRE = eINSTANCE.getUnoOlypique_DistributionAleatoire();

    /**
     * The meta object literal for the '<em><b>Sens Defini</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__SENS_DEFINI = eINSTANCE.getUnoOlypique_SensDefini();

    /**
     * The meta object literal for the '<em><b>Changement Donneur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__CHANGEMENT_DONNEUR = eINSTANCE.getUnoOlypique_ChangementDonneur();

    /**
     * The meta object literal for the '<em><b>Vue Des Cartes Apres1er Pose</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__VUE_DES_CARTES_APRES1ER_POSE = eINSTANCE.getUnoOlypique_VueDesCartesApres1erPose();

    /**
     * The meta object literal for the '<em><b>Donneur Premierose</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__DONNEUR_PREMIEROSE = eINSTANCE.getUnoOlypique_DonneurPremierose();

    /**
     * The meta object literal for the '<em><b>Jeu Rapide</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__JEU_RAPIDE = eINSTANCE.getUnoOlypique_JeuRapide();

    /**
     * The meta object literal for the '<em><b>Interception</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__INTERCEPTION = eINSTANCE.getUnoOlypique_Interception();

    /**
     * The meta object literal for the '<em><b>Deux Cartes Identiques</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__DEUX_CARTES_IDENTIQUES = eINSTANCE.getUnoOlypique_DeuxCartesIdentiques();

    /**
     * The meta object literal for the '<em><b>Decision Carte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__DECISION_CARTE = eINSTANCE.getUnoOlypique_DecisionCarte();

    /**
     * The meta object literal for the '<em><b>Surenchere</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__SURENCHERE = eINSTANCE.getUnoOlypique_Surenchere();

    /**
     * The meta object literal for the '<em><b>Cartezero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__CARTEZERO = eINSTANCE.getUnoOlypique_Cartezero();

    /**
     * The meta object literal for the '<em><b>Carte Sept</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__CARTE_SEPT = eINSTANCE.getUnoOlypique_CarteSept();

    /**
     * The meta object literal for the '<em><b>Carte2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__CARTE2 = eINSTANCE.getUnoOlypique_Carte2();

    /**
     * The meta object literal for the '<em><b>Valeur Carte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_OLYPIQUE__VALEUR_CARTE = eINSTANCE.getUnoOlypique_ValeurCarte();

    /**
     * The meta object literal for the '{@link org.xtext.example.unotext.unoText.impl.UnoWizzImpl <em>Uno Wizz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.unotext.unoText.impl.UnoWizzImpl
     * @see org.xtext.example.unotext.unoText.impl.UnoTextPackageImpl#getUnoWizz()
     * @generated
     */
    EClass UNO_WIZZ = eINSTANCE.getUnoWizz();

    /**
     * The meta object literal for the '<em><b>Presqu Uno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_WIZZ__PRESQU_UNO = eINSTANCE.getUnoWizz_PresquUno();

    /**
     * The meta object literal for the '<em><b>Chiffre Moins</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_WIZZ__CHIFFRE_MOINS = eINSTANCE.getUnoWizz_ChiffreMoins();

    /**
     * The meta object literal for the '<em><b>Couleur Moins</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_WIZZ__COULEUR_MOINS = eINSTANCE.getUnoWizz_CouleurMoins();

    /**
     * The meta object literal for the '<em><b>Carte Rouge</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_WIZZ__CARTE_ROUGE = eINSTANCE.getUnoWizz_CarteRouge();

  }

} //UnoTextPackage
