/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.unotext.unoText.UnoTextPackage
 * @generated
 */
public interface UnoTextFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UnoTextFactory eINSTANCE = org.xtext.example.unotext.unoText.impl.UnoTextFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Uno</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno</em>'.
   * @generated
   */
  Uno createUno();

  /**
   * Returns a new object of class '<em>Uno Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno Rule</em>'.
   * @generated
   */
  Uno_Rule createUno_Rule();

  /**
   * Returns a new object of class '<em>Uno Classic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno Classic</em>'.
   * @generated
   */
  Uno_Classic createUno_Classic();

  /**
   * Returns a new object of class '<em>Carte Identique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Carte Identique</em>'.
   * @generated
   */
  CarteIdentique createCarteIdentique();

  /**
   * Returns a new object of class '<em>Cumul Ajout</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cumul Ajout</em>'.
   * @generated
   */
  CumulAjout createCumulAjout();

  /**
   * Returns a new object of class '<em>Uno Olypique</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno Olypique</em>'.
   * @generated
   */
  UnoOlypique createUnoOlypique();

  /**
   * Returns a new object of class '<em>Uno Wizz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uno Wizz</em>'.
   * @generated
   */
  UnoWizz createUnoWizz();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UnoTextPackage getUnoTextPackage();

} //UnoTextFactory
