/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.unoText;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno Wizz</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoWizz#getPresquUno <em>Presqu Uno</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoWizz#getChiffreMoins <em>Chiffre Moins</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoWizz#getCouleurMoins <em>Couleur Moins</em>}</li>
 *   <li>{@link org.xtext.example.unotext.unoText.UnoWizz#getCarteRouge <em>Carte Rouge</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoWizz()
 * @model
 * @generated
 */
public interface UnoWizz extends Uno_Rule
{
  /**
   * Returns the value of the '<em><b>Presqu Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Presqu Uno</em>' attribute.
   * @see #setPresquUno(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoWizz_PresquUno()
   * @model
   * @generated
   */
  String getPresquUno();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoWizz#getPresquUno <em>Presqu Uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Presqu Uno</em>' attribute.
   * @see #getPresquUno()
   * @generated
   */
  void setPresquUno(String value);

  /**
   * Returns the value of the '<em><b>Chiffre Moins</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chiffre Moins</em>' attribute.
   * @see #setChiffreMoins(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoWizz_ChiffreMoins()
   * @model
   * @generated
   */
  String getChiffreMoins();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoWizz#getChiffreMoins <em>Chiffre Moins</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chiffre Moins</em>' attribute.
   * @see #getChiffreMoins()
   * @generated
   */
  void setChiffreMoins(String value);

  /**
   * Returns the value of the '<em><b>Couleur Moins</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Couleur Moins</em>' attribute.
   * @see #setCouleurMoins(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoWizz_CouleurMoins()
   * @model
   * @generated
   */
  String getCouleurMoins();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoWizz#getCouleurMoins <em>Couleur Moins</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Couleur Moins</em>' attribute.
   * @see #getCouleurMoins()
   * @generated
   */
  void setCouleurMoins(String value);

  /**
   * Returns the value of the '<em><b>Carte Rouge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Carte Rouge</em>' attribute.
   * @see #setCarteRouge(String)
   * @see org.xtext.example.unotext.unoText.UnoTextPackage#getUnoWizz_CarteRouge()
   * @model
   * @generated
   */
  String getCarteRouge();

  /**
   * Sets the value of the '{@link org.xtext.example.unotext.unoText.UnoWizz#getCarteRouge <em>Carte Rouge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Carte Rouge</em>' attribute.
   * @see #getCarteRouge()
   * @generated
   */
  void setCarteRouge(String value);

} // UnoWizz
