/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UnoTextStandaloneSetup extends UnoTextStandaloneSetupGenerated {

	public static void doSetup() {
		new UnoTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
