/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUnoTextScopeProvider extends DelegatingScopeProvider {
}
