/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.unotext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.unotext.parser.antlr.internal.InternalUnoTextParser;
import org.xtext.example.unotext.services.UnoTextGrammarAccess;

public class UnoTextParser extends AbstractAntlrParser {

	@Inject
	private UnoTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUnoTextParser createParser(XtextTokenStream stream) {
		return new InternalUnoTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Uno";
	}

	public UnoTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UnoTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
